config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  as :user do
    get 'signin' => 'static_pages#root', as: :new_user_session
    delete 'signout' => 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :journals, only: [:index] do
    collection do
      post :sync
    end
    member do
      post :push_category
    end
  end

  resources :teams, only: [:index]
  resources :authors, only: [:index, :update]

  resource :teamwork_api_key, only: [:new, :create, :edit, :update]

  post 'teamwork/hook' => 'webhooks#teamwork'

  root to: 'static_pages#root'
end

app/controllers/teamwork_api_keys_controller.rb
class TeamworkApiKeysController < ApplicationController
  skip_before_filter :require_teamwork_api_key!

  def new
  end

  def create
    current_user.update teamwork_api_key: params[:teamwork_api_key]
    # TODO: validate key against teamwork, more robust job system
    SyncJob.new.async.perform current_user.id
    flash[:success] = "Added a Teamwork key. Data should sync momentarily. Try refreshing."
    redirect_to session.delete(:post_teamwork_api_key_return) || journals_path
  end
end

app/views/teamwork_api_keys/new.html.slim
.alert.alert-success In order to access Teamwork, you'll need to configure and store an API key. Visit #{link_to 'Teamwork', teamwork_url} and click <code>Edit my details</code> > <code>API</code> to create or retrieve one.

.col-lg-6
  = form_tag teamwork_api_key_path, class: "form" do
    .input-group
      = password_field_tag "teamwork_api_key", nil, placeholder: "Teamwork API key", required: true, class: "form-control"
      span.input-group-btn
        button.btn.btn-primary Save