config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  as :user do
    get 'signin' => 'static_pages#root', as: :new_user_session
    delete 'signout' => 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :journals, only: [:index] do
    collection do
      post :sync
    end
    member do
      post :push_category
    end
  end

  resources :teams, only: [:index]
  resources :authors, only: [:index, :update]

  resource :teamwork_api_key, only: [:new, :create, :edit, :update]

  post 'teamwork/hook' => 'webhooks#teamwork'

  root to: 'static_pages#root'
end

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? "#{yield :title} | TIY Journals" : "TIY Journals"

    = csrf_meta_tags

    = javascript_include_tag "application"
    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"

    = stylesheet_link_tag "//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css"
    = stylesheet_link_tag "application", media: "all"
  body
    nav.navbar.navbar-default
      .container
        .navbar-header
          a.navbar-brand href="/"
            = icon :book
            '  Scrivener

        ul.nav.navbar-nav
          li= link_to 'Journals', journals_path
          li= link_to 'Authors', authors_path

        ul.nav.navbar-nav.navbar-right
          - if current_user
            li
              a= current_user.gh_username
            li= link_to "Log out", destroy_user_session_path, method: :delete
          - else
            li
              = link_to user_omniauth_authorize_path(:github) do
                = icon :github
                ' Log in

    .container
      .flash
        - flash.each do |name, msg|
          div class="alert alert-#{flash_class name}"
            a.close data-dismiss="alert"
              | &times;
            div id="flash_#{flash_class name}"
              = msg

      = yield